services:
  postgres:
    image: postgres:16-alpine
    container_name: go-file-explorer-db
    environment:
      POSTGRES_USER: explorer
      POSTGRES_PASSWORD: explorer
      POSTGRES_DB: file_explorer
    ports:
      - "5432:5432"
    volumes:
      - /mnt/datos-externos/file-explorer-data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U explorer -d file_explorer"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-file-explorer-api
    env_file:
      - path: .env.example
        required: true
      - path: .env
        required: false
    environment:
      STORAGE_ROOT: /data
      DATABASE_URL: postgres://explorer:explorer@postgres:5432/file_explorer?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - /mnt/datos-externos/file-explorer-data/data:/data
      - /mnt/datos-externos/file-explorer-data/state:/app/state
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

